"""Checker for 10-partition-the-firehose.

Run from the module root, AFTER applying your src/migrate.sql against the
live database yourself:
    uv run python 10-partition-the-firehose/tests/check.py

This checker is structural-first: it inspects whatever state
`inventory_events` is currently in on the live DB. It does not run any
migration for you and does not roll anything back.

Verifies, in order:
  1. inventory_events is a partitioned table, strategy RANGE.
  2. Partition count is sane for the data's time span, and at least one
     partition's bounds lie entirely in the future relative to the stock
     max(occurred_at).
  3. Data parity: count(*), sum(qty_delta), min/max(occurred_at) match the
     stock values (hardcoded below -- see the comment for how/when they
     were captured).
  4. Partition pruning: a bounded last-14-days query touches at most
     MAX_SCANNED_PARTITIONS child relations.
  5. Timing vs. a stock-recorded baseline is reported as info only (see
     tests-w3a authoring notes for why this is not a hard pass/fail gate).
"""

import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "tools"))

import psycopg  # noqa: E402

from plan_check import conninfo, get_plan  # noqa: E402
import baseline  # noqa: E402

MODULE_ROOT = Path(__file__).resolve().parents[2]
BASELINE_FILE = MODULE_ROOT / "baseline-local.json"
RECENT_WINDOW_QUERY_ID = "recent_window_stock"

# Stock values captured live against the unpartitioned table on 2026-07-08,
# SCALE=1.0 default seed. These hold for the stock DB as generated by
# seed/generate.py and do not change unless the seed is regenerated.
STOCK_COUNT = 9_000_000
STOCK_SUM_QTY_DELTA = 183_651_745
STOCK_MIN_OCCURRED_AT = datetime(2025, 1, 10, 7, 21, 23)
STOCK_MAX_OCCURRED_AT = datetime(2026, 7, 8, 11, 59, 59)

# Jan 2025 through Jul 2026 inclusive = 19 calendar months of real data;
# the migration must add at least one more (entirely future) month.
MIN_PARTITIONS = 20
MAX_SCANNED_PARTITIONS = 2

RECENT_WINDOW_SQL = (
    "SELECT count(*) FROM inventory_events "
    "WHERE occurred_at >= now() - interval '14 days' AND occurred_at <= now()"
)


def fail(reason):
    print(f"FAIL  {reason}")
    print(f"NOT PASSED: {reason}")
    sys.exit(1)


def iter_plan_nodes(node):
    yield node
    for child in node.get("Plans", []):
        yield from iter_plan_nodes(child)


def main():
    try:
        conn = psycopg.connect(conninfo())
    except psycopg.Error as e:
        print(f"NOT PASSED: could not connect: {e}")
        sys.exit(1)

    with conn.cursor() as cur:
        # --- 1. is it partitioned, and by RANGE? --------------------------
        cur.execute(
            """
            SELECT p.partstrat
            FROM pg_partitioned_table p
            JOIN pg_class c ON c.oid = p.partrelid
            WHERE c.relname = 'inventory_events'
            """
        )
        row = cur.fetchone()
        if row is None:
            fail(
                "inventory_events is not a partitioned table -- "
                "apply src/migrate.sql against the live database first"
            )
        if row[0] != "r":
            fail(f"inventory_events is partitioned, but strategy is '{row[0]}', expected RANGE ('r')")
        print("PASS  inventory_events is RANGE-partitioned")

        # --- 2. partition count + bounds -----------------------------------
        cur.execute(
            """
            SELECT c.relname, pg_get_expr(c.relpartbound, c.oid)
            FROM pg_inherits i
            JOIN pg_class parent ON parent.oid = i.inhparent
            JOIN pg_class c ON c.oid = i.inhrelid
            WHERE parent.relname = 'inventory_events'
            """
        )
        children = cur.fetchall()

    conn.close()

    if len(children) < MIN_PARTITIONS:
        fail(
            f"only {len(children)} partitions found, expected at least {MIN_PARTITIONS} "
            "to cover the full ~19-month data span plus a future month"
        )
    print(f"PASS  {len(children)} partitions found (>= {MIN_PARTITIONS})")

    ts_re = re.compile(r"'([^']+)'")
    has_future = False
    for _, bound_expr in children:
        if not bound_expr:
            continue
        matches = ts_re.findall(bound_expr)
        if len(matches) < 1:
            continue
        try:
            lower = datetime.fromisoformat(matches[0])
        except ValueError:
            continue
        if lower > STOCK_MAX_OCCURRED_AT:
            has_future = True
            break

    if not has_future:
        fail(
            "no partition has a lower bound strictly after the stock max(occurred_at) "
            f"({STOCK_MAX_OCCURRED_AT}) -- add at least one wholly-future month so the "
            "retention story (new months arrive with a ready-made partition) actually holds"
        )
    print("PASS  at least one partition lies entirely in the future")

    # --- 3. data parity -----------------------------------------------------
    with psycopg.connect(conninfo()) as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT count(*), sum(qty_delta), min(occurred_at), max(occurred_at) "
                "FROM inventory_events"
            )
            count, sum_qty, min_at, max_at = cur.fetchone()

    parity_errors = []
    if count != STOCK_COUNT:
        parity_errors.append(f"count(*) = {count}, expected {STOCK_COUNT}")
    if sum_qty != STOCK_SUM_QTY_DELTA:
        parity_errors.append(f"sum(qty_delta) = {sum_qty}, expected {STOCK_SUM_QTY_DELTA}")
    if min_at != STOCK_MIN_OCCURRED_AT:
        parity_errors.append(f"min(occurred_at) = {min_at}, expected {STOCK_MIN_OCCURRED_AT}")
    if max_at != STOCK_MAX_OCCURRED_AT:
        parity_errors.append(f"max(occurred_at) = {max_at}, expected {STOCK_MAX_OCCURRED_AT}")

    if parity_errors:
        fail("data parity broken after migration -- " + "; ".join(parity_errors))
    print("PASS  count/sum/min/max match the stock table exactly")

    # --- 4. pruning -----------------------------------------------------
    try:
        plan = get_plan(RECENT_WINDOW_SQL, analyze=False)
    except psycopg.Error as e:
        fail(f"could not obtain plan for the recent-window query: {e}")

    scanned = {
        n.get("Relation Name")
        for n in iter_plan_nodes(plan["Plan"])
        if n.get("Relation Name") and n.get("Relation Name") != "inventory_events"
    }
    if len(scanned) > MAX_SCANNED_PARTITIONS:
        fail(
            f"last-14-days query touches {len(scanned)} child relations "
            f"({sorted(scanned)}), expected <= {MAX_SCANNED_PARTITIONS} -- "
            "partition pruning is not eliminating the older/future partitions"
        )
    print(
        f"PASS  last-14-days query touches only {len(scanned)} partition(s) "
        f"(<= {MAX_SCANNED_PARTITIONS}) -- pruning works"
    )

    # --- 5. timing: informational only, see .authoring/tasks-w3a.md --------
    data = baseline.load_baseline(BASELINE_FILE)
    if RECENT_WINDOW_QUERY_ID in data:
        base_ms = data[RECENT_WINDOW_QUERY_ID]["median_ms"]
        try:
            timings = baseline.time_query(RECENT_WINDOW_SQL, runs=5, warmups=1)
            import statistics

            median = statistics.median(timings)
            speedup = base_ms / median if median > 0 else float("inf")
            print(
                f"info  recent-window query: {median:.1f} ms vs stock baseline "
                f"{base_ms:.1f} ms -> {speedup:.2f}x (informational only, not a pass/fail gate)"
            )
        except psycopg.Error as e:
            print(f"info  could not time recent-window query: {e}")
    else:
        print(
            "info  no stock baseline recorded for the recent-window query "
            f"(optional: uv run python tools/baseline.py record <file> --id {RECENT_WINDOW_QUERY_ID})"
        )

    print("PASSED")
    sys.exit(0)


if __name__ == "__main__":
    main()
