{#
    Given/GIVEN infra macro, not part of the exercise.

    dbt's default generate_schema_name concatenates the profile's target
    schema and a model's custom +schema config (e.g. "dbt_analytics_staging").
    This override replaces that behavior: when a model sets +schema, the
    resulting schema is exactly that name, nothing prefixed or appended.
    This keeps every dbt-created relation inside the two dedicated schemas
    named in dbt_project.yml (dbt_analytics, dbt_analytics_marts) and out of
    module 02's source schemas. Do not edit this file.
#}
{% macro generate_schema_name(custom_schema_name, node) -%}
    {%- if custom_schema_name is none -%}
        {{ target.schema }}
    {%- else -%}
        {{ custom_schema_name | trim }}
    {%- endif -%}
{%- endmacro %}
