"""Correct, GIVEN implementation of an in-process LRU cache with TTL expiry.

Do not edit this file. It is not the deliverable — the task is to write a
TEST SUITE that would catch a regression in this class, not to change the
class itself.

Semantics (read carefully — your tests should encode every one of these):

- Capacity: the cache holds at most `capacity` live entries. Inserting a
  brand-new key when the cache already holds `capacity` live entries
  evicts the LEAST RECENTLY USED entry first.
- Recency: recency is updated by (a) `put` of a brand-new key, (b) `put`
  of a key that already exists (an update refreshes it to
  most-recently-used, it is not treated as a no-op for ordering purposes),
  and (c) a `get` that hits a live entry. A `get` that misses (absent key,
  or a present-but-expired key) does NOT change anything's recency.
- TTL: every `put` stamps the entry with an absolute expiry deadline,
  `clock() + ttl`, computed at the moment of that call. An entry is
  EXPIRED once `clock() >= deadline` — the deadline instant itself already
  counts as expired, not the last live instant. So an entry inserted at
  t=0 with ttl=5 is live for any `get`/`len` observing clock() in [0, 5),
  and is expired from clock() == 5 onward.
- Expired entries are treated exactly like absent keys everywhere they are
  observed, and are lazily purged from internal storage the next time any
  method notices them — there is no background sweep.
- `clock` is injectable specifically so tests can control time
  deterministically (advance a fake clock step by step) instead of
  sleeping in real time. Defaults to `time.monotonic`.
- `__len__` reports the number of LIVE (non-expired) entries only. An
  expired-but-not-yet-purged entry must never be counted.
"""

from __future__ import annotations

import time
from collections import OrderedDict
from typing import Callable, Hashable, Optional


class TTLCache:
    def __init__(
        self,
        capacity: int,
        ttl: float,
        clock: Callable[[], float] = time.monotonic,
    ) -> None:
        if capacity < 1:
            raise ValueError("capacity must be >= 1")
        if ttl <= 0:
            raise ValueError("ttl must be > 0")
        self._capacity = capacity
        self._ttl = ttl
        self._clock = clock
        # key -> (value, deadline); dict order == recency, oldest (LRU) first
        self._store: "OrderedDict[Hashable, tuple[object, float]]" = OrderedDict()

    def _is_expired(self, deadline: float) -> bool:
        return self._clock() >= deadline

    def _purge_expired(self) -> None:
        expired = [k for k, (_, deadline) in self._store.items() if self._is_expired(deadline)]
        for k in expired:
            del self._store[k]

    def put(self, key: Hashable, value: object) -> None:
        self._purge_expired()
        deadline = self._clock() + self._ttl
        self._store[key] = (value, deadline)
        self._store.move_to_end(key)
        if len(self._store) > self._capacity:
            self._store.popitem(last=False)

    def get(self, key: Hashable) -> Optional[object]:
        self._purge_expired()
        entry = self._store.get(key)
        if entry is None:
            return None
        value, deadline = entry
        if self._is_expired(deadline):
            del self._store[key]
            return None
        self._store.move_to_end(key)
        return value

    def __len__(self) -> int:
        self._purge_expired()
        return len(self._store)
