"""Subprocess-based mutant-killing engine shared by every task in this
module (except 06, which grades via the real `cosmic-ray` tool directly --
see .authoring/design.md for that exception).

A task's `tests/validate.py` is a thin call into `grade()`. The protocol:

  1. Run the learner's test suite against the CORRECT implementation. It
     must fully pass and must collect at least `min_tests` tests (the
     green-on-correct gate + the non-triviality gate -- an empty or
     always-failing suite is rejected here).
  2. Run the same suite against every mutant in `mutant_dir`, one fresh
     `python -m pytest` subprocess per mutant (no import caching across
     mutants -- each subprocess re-imports the SUT shim from scratch).
  3. A mutant that the suite still PASSES against has SURVIVED (bad, the
     suite would not catch that regression in production). A mutant that
     makes the suite FAIL has been KILLED (good).
  4. If every mutant is killed, PASSED. Otherwise NOT PASSED, naming the
     surviving mutants by their generic filename (never by their bug, so
     the failure message is not itself a spoiler).

Canonical task layout this module assumes (see .authoring/design.md):

    NN-task-name/
      src/
        impl.py        # GIVEN correct implementation
        sut.py          # generated by write_sut_shim() -- learner imports THIS
      tests/
        test_*.py       # learner-authored
        validate.py     # `from harness.mutation import grade; grade(...)`

  .authoring/mutants/NN-task-name/*.py   # mutant bank, off-limits to the learner

Tests are always invoked as `python -m pytest <paths> -q`, run with
cwd=<task dir>, and NEVER as the bare `pytest` executable. This matters on
Windows: `python -m X` inserts the current working directory as
sys.path[0] before pytest even starts, which is what makes the namespace
package `src` (no `src/__init__.py` needed) importable as `src.sut` without
any extra sys.path surgery or conftest.py. Using `sys.executable` also
sidesteps a real Windows gotcha we hit while proving this out: a bare
`python` on PATH inside a subprocess can resolve to a *different*
interpreter than the project's venv (see the cosmic-ray section of
design.md) -- always launch tests via `[sys.executable, "-m", "pytest",
...]`, never via a bare `"python"` string.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from harness.common import not_passed, passed

DEFAULT_TIMEOUT = 300

# pytest -q suppresses the "collected N items" header; the reliable place
# to recover the test count is the final summary line, e.g.
# "3 passed, 1 failed in 0.42s" or "5 passed in 0.19s". Scanning only the
# last few lines (not the whole output) avoids false matches inside a
# learner's traceback text that happens to contain e.g. "2 passed".
_SUMMARY_COUNT_RE = re.compile(r"(\d+) (passed|failed|errors?|skipped|xfailed|xpassed)")
_TAIL_LINES = 40
_SUMMARY_SCAN_LINES = 5


@dataclass
class SuiteResult:
    passed: bool
    returncode: int
    collected: int
    output_tail: str
    timed_out: bool = False


def _parse_collected(output: str) -> int:
    summary_area = "\n".join(output.splitlines()[-_SUMMARY_SCAN_LINES:])
    return sum(int(n) for n, _ in _SUMMARY_COUNT_RE.findall(summary_area))


def _tail(output: str, n: int = _TAIL_LINES) -> str:
    lines = output.splitlines()
    return "\n".join(lines[-n:])


def run_suite(
    test_paths: list[str],
    impl_path: str | None,
    cwd: str,
    extra_env: dict | None = None,
    timeout: int = DEFAULT_TIMEOUT,
    fail_fast: bool = False,
) -> SuiteResult:
    """Run the learner's suite against one implementation in a fresh subprocess.

    `impl_path`, if given, is exported as SUT_IMPL_PATH -- the SUT shim
    (src/sut.py) reads this env var to decide which implementation to
    re-export. `impl_path=None` means "let the shim fall back to its
    default `impl` module" (the correct, unmutated implementation).

    `fail_fast=True` adds `-x` (stop at first failure) -- use it when
    grading mutants, where only pass/fail matters and speed matters more
    than a full failure count. Never use it for the correct-impl run: that
    run also needs the true `collected` count for the non-triviality gate,
    and `-x` does not affect collection, but keep it off there anyway for a
    clean, complete result.
    """
    env = os.environ.copy()
    if impl_path is not None:
        env["SUT_IMPL_PATH"] = str(impl_path)
    else:
        env.pop("SUT_IMPL_PATH", None)
    if extra_env:
        env.update(extra_env)

    cmd = [sys.executable, "-m", "pytest", *test_paths, "-q"]
    if fail_fast:
        cmd.append("-x")

    try:
        proc = subprocess.run(
            cmd, cwd=cwd, env=env, capture_output=True, text=True, timeout=timeout
        )
    except subprocess.TimeoutExpired as exc:
        stdout = (exc.stdout or "") if isinstance(exc.stdout, str) else (exc.stdout or b"").decode(errors="replace")
        output = stdout + f"\n[TIMEOUT after {timeout}s]"
        return SuiteResult(
            passed=False,
            returncode=-1,
            collected=_parse_collected(stdout),
            output_tail=_tail(output),
            timed_out=True,
        )

    output = proc.stdout + proc.stderr
    return SuiteResult(
        passed=proc.returncode == 0,
        returncode=proc.returncode,
        collected=_parse_collected(output),
        output_tail=_tail(output),
    )


def _iter_mutant_files(mutant_dir: str) -> list[Path]:
    paths = sorted(Path(mutant_dir).glob("*.py"))
    return [p for p in paths if p.name != "__init__.py" and not p.name.startswith("_")]


def grade(
    test_paths: list[str],
    correct_impl: str,
    mutant_dir: str,
    cwd: str,
    min_tests: int = 1,
    required_kill_ratio: float = 1.0,
    extra_env: dict | None = None,
    timeout: int = DEFAULT_TIMEOUT,
) -> None:
    """Full mutant-killing grading protocol. Ends the process via
    `harness.common.passed`/`not_passed` -- call this as the entire body of
    a task's `tests/validate.py`.

    A per-mutant timeout is treated as KILLED (the mutant broke something
    badly enough to hang the suite -- that is still a suite that would
    catch the regression, just noisily) but is called out by id in the
    success detail line so a task author can notice a mutant that should
    probably be redesigned to fail fast instead of hanging.
    """
    baseline = run_suite(test_paths, correct_impl, cwd, extra_env=extra_env, timeout=timeout, fail_fast=False)

    if baseline.timed_out:
        not_passed(f"your test suite timed out after {timeout}s against the correct implementation")
    if not baseline.passed:
        not_passed(
            "your tests must pass against the correct implementation "
            f"(pytest exit code {baseline.returncode}):\n{baseline.output_tail}"
        )
    if baseline.collected < min_tests:
        not_passed(f"found only {baseline.collected} test(s) -- write at least {min_tests}")

    mutant_files = _iter_mutant_files(mutant_dir)
    if not mutant_files:
        not_passed("no mutants found to grade against (internal error -- contact the task author)")

    survivors: list[str] = []
    timed_out_ids: list[str] = []

    for mutant_path in mutant_files:
        mutant_id = mutant_path.stem
        result = run_suite(
            test_paths, str(mutant_path), cwd, extra_env=extra_env, timeout=timeout, fail_fast=True
        )
        if result.timed_out:
            timed_out_ids.append(mutant_id)
            continue
        if result.passed:
            survivors.append(mutant_id)

    total = len(mutant_files)
    killed = total - len(survivors)
    ratio = killed / total

    if ratio < required_kill_ratio:
        ids = ", ".join(survivors)
        not_passed(f"{len(survivors)} mutant(s) survived: {ids}. Your suite does not catch these regressions.")

    detail = f"killed {killed}/{total} mutants"
    if timed_out_ids:
        detail += f" ({len(timed_out_ids)} counted as killed via timeout: {', '.join(timed_out_ids)})"
    passed(detail)


SUT_SHIM_TEMPLATE = '''"""Auto-generated SUT shim -- DO NOT EDIT BY HAND.

Exposes the implementation under test as `src.sut`. Learner tests must
import from here (`from src.sut import name` or `import src.sut as sut`),
never from `src.impl` directly -- that indirection is what lets the grading
harness swap in a mutant by setting SUT_IMPL_PATH before this module is
imported. Regenerate with harness.mutation.write_sut_shim if this file is
ever lost or the task's public API changes.
"""

import importlib.util
import os

_impl_path = os.environ.get("SUT_IMPL_PATH")

if _impl_path:
    _spec = importlib.util.spec_from_file_location("_sut_impl_external", _impl_path)
    _mod = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(_mod)
else:
    from . import impl as _mod

{export_line}
'''


def write_sut_shim(dst_path: str | Path, public_names: list[str] | None = None) -> None:
    """Generate a task's `src/sut.py` from SUT_SHIM_TEMPLATE.

    `public_names`, if given, restricts the re-export to exactly those
    names (useful when `impl.py` has helper names that should not leak
    into the learner-facing API). If omitted, every name in the loaded
    module that does not start with `_` is re-exported -- the common case.
    """
    if public_names is None:
        export_line = (
            "globals().update({k: v for k, v in vars(_mod).items() if not k.startswith('_')})"
        )
    else:
        names_repr = ", ".join(repr(n) for n in public_names)
        export_line = (
            f"_PUBLIC_NAMES = ({names_repr},)\n"
            "globals().update({k: v for k, v in vars(_mod).items() if k in _PUBLIC_NAMES})"
        )

    content = SUT_SHIM_TEMPLATE.format(export_line=export_line)
    dst = Path(dst_path)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(content, encoding="utf-8")
