"""Provided workloads for the GIL decision matrix -- fully implemented, not
a stub. You implement `src/runners.py`, which runs these two functions
three ways each (sequential, threads, processes -- plus asyncio for the I/O
one) so `baseline.py` can measure, on your own machine, where the GIL
actually costs you something and where it doesn't.

Both functions are module-top-level so they are picklable -- required for
`ProcessPoolExecutor`, which sends the callable and its arguments to a
worker process by pickling them across the process boundary.

Do not edit this file; the point of the task is `runners.py`, not this.
"""

import math
import time

# Tuned so a single cpu_bound() call takes roughly 0.4-0.5s on a modern
# machine and a batch of BATCH_SIZE calls gives sequential/threaded/
# multiprocess runs each a few hundred ms to multiple seconds -- long
# enough for a real ProcessPoolExecutor speedup to show up above the noise
# of process-pool startup, short enough that the whole baseline finishes in
# well under a minute.
CPU_N = 2_000_000

# Tuned so a single io_bound() call is clearly longer than scheduling
# overhead but the whole batch still finishes in well under a second when
# run concurrently.
IO_DELAY = 0.08

# Number of calls per strategy per workload in baseline.py.
BATCH_SIZE = 8


def cpu_bound(n: int = CPU_N) -> float:
    """A genuinely CPU-bound pure-Python computation: sums a trig/sqrt
    transform over range(1, n+1) in a plain Python loop.

    Deliberately NOT vectorized with numpy. A numpy call like `np.sin(arr)`
    drops into a C loop that releases the GIL for the duration of the call,
    which would make this workload behave like the I/O-bound one under
    threads -- defeating the point of this task. Every iteration here stays
    in the Python interpreter loop, holding the GIL essentially the entire
    time this function runs. That's what makes it representative of
    "CPU-bound pure-Python work" as opposed to "CPU-bound work that happens
    to call into C."

    Returns the accumulated sum (not used for anything -- callers only care
    about wall-clock time), so the loop can't be optimized away.
    """
    total = 0.0
    for i in range(1, n + 1):
        total += math.sin(i) * math.sqrt(i)
    return total


def io_bound(delay: float = IO_DELAY) -> float:
    """Simulates a blocking I/O call (a network request, a disk read, a
    query) with a plain `time.sleep()`.

    `time.sleep()` releases the GIL for its duration -- the interpreter is
    free to run other threads while this one is parked in the OS scheduler.
    That's the property this workload exists to demonstrate: unlike
    `cpu_bound`, this one does NOT hold the GIL for the bulk of its runtime.

    Returns `delay` (not used for anything -- callers only care about
    wall-clock time).
    """
    time.sleep(delay)
    return delay
