"""Back-of-the-envelope capacity model for the 10k-site price monitor.

Every function takes the workload dict (loaded from `workload.json`, see the
task README for its schema) as its single argument, so the validator can
call the same function against perturbed copies of the workload. The exact
formula, rounding rule, and unit for each function is pinned in the task
README's "Capacity model contract" section — implement each function to
match that spec exactly. Do not guess a convention that isn't written down
there.

None of these functions take any argument besides `w`. None of them read
files, print, or have side effects — they are pure arithmetic over `w`.
"""

from __future__ import annotations


def daily_fetch_attempts(w: dict) -> float:
    """Total fetch attempts across all tiers per day, including retries.

    Units: attempts / day (a float — this is an expected value, not a
    count of anything that actually happened, so it is not rounded to an
    integer).
    """
    raise NotImplementedError


def average_fetches_per_second(w: dict) -> float:
    """Average fetch-attempt rate over a full day.

    Units: attempts / second, unrounded.
    """
    raise NotImplementedError


def peak_fetches_per_second(w: dict) -> float:
    """Fetch-attempt rate during the busiest hours of the day.

    Units: attempts / second, unrounded.
    """
    raise NotImplementedError


def required_concurrency(w: dict) -> float:
    """In-flight fetch capacity the fleet must provision for at peak.

    Units: concurrent in-flight requests, unrounded (this is the raw
    provisioning target before it gets packed into whole pods).
    """
    raise NotImplementedError


def pod_count(w: dict) -> int:
    """Number of worker pods needed to cover the peak concurrency target.

    Units: whole pods. Rounding rule: round UP to the nearest whole pod
    (a fractional pod is not deployable).
    """
    raise NotImplementedError


def egress_bytes_per_day(w: dict) -> float:
    """Total proxy egress traffic generated by fetch attempts in one day.

    Units: bytes / day, unrounded.
    """
    raise NotImplementedError


def monthly_proxy_cost_usd(w: dict) -> float:
    """Projected monthly proxy bill implied by the egress volume.

    Units: US dollars / month, unrounded.
    """
    raise NotImplementedError
