//! `sandbox18-harness` — GIVEN support scaffolding for the `18-rust-track` module.
//!
//! This crate is never a solution to any task. It is infrastructure shared by
//! every task in the module: loading the ground-truth answer key generated by
//! `sandbox18-datagen`, a local HTTP/1.1 fixture server (blocking and, behind
//! the `async` feature, tokio-based) so tasks never need a real network or an
//! HTTP client crate, a small deterministic PRNG, and a scoped temp-dir helper.
//!
//! Learners do not modify this crate. Task crates depend on it via
//! `sandbox18-harness = { workspace = true }` and, for the async variant,
//! additionally enable the `async` feature.

pub mod fixture_server;
pub mod ground_truth;
pub mod prng;
pub mod tempdir;

#[cfg(feature = "async")]
pub mod async_fixture_server;
