-- Kupitron marketplace schema.
-- This schema is DELIBERATELY wrecked in specific, documented ways.
-- See ../.authoring/ for the full list of planted defects (spoilers).
-- Do not "fix" anything here manually while working on module tasks — the
-- defects are the curriculum.

DROP TABLE IF EXISTS inventory_events CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS sellers CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       TEXT NOT NULL,
    full_name   TEXT NOT NULL,
    city        TEXT NOT NULL,
    country     TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX idx_users_email ON users (email);

-- ---------------------------------------------------------------------------
-- sellers
-- ---------------------------------------------------------------------------
CREATE TABLE sellers (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    tier        VARCHAR(10) NOT NULL,
    rating      NUMERIC(3,2) NOT NULL,
    created_at  TIMESTAMP NOT NULL
);

-- ---------------------------------------------------------------------------
-- categories (tree)
-- ---------------------------------------------------------------------------
CREATE TABLE categories (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   INTEGER REFERENCES categories (id),
    name        TEXT NOT NULL,
    family      VARCHAR(20) NOT NULL,
    depth       SMALLINT NOT NULL
);

CREATE INDEX idx_categories_parent_id ON categories (parent_id);

-- ---------------------------------------------------------------------------
-- products
-- Defect (d): attrs JSONB queried with @> / ->>'brand' but no GIN index.
--             title searched with ILIKE '%term%', no trigram index.
-- ---------------------------------------------------------------------------
CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id   INTEGER NOT NULL REFERENCES sellers (id),
    category_id INTEGER NOT NULL REFERENCES categories (id),
    title       TEXT NOT NULL,
    price       NUMERIC(12,2) NOT NULL,
    attrs       JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMP NOT NULL
);

CREATE INDEX idx_products_seller_id ON products (seller_id);
CREATE INDEX idx_products_category_id ON products (category_id);
-- Deliberately NO GIN index on attrs, NO pg_trgm index on title.

-- ---------------------------------------------------------------------------
-- orders
-- Defect (a): index on (status) alone (low cardinality) but no index on
--             (user_id, created_at) — user order-history queries seq-scan.
-- Defect (h): user_id BIGINT vs users.id INTEGER (cast on join); money as
--             numeric(30,10); status as varchar(10) instead of an enum.
-- Defect (f): autovacuum delayed at table level -> churn phase leaves bloat.
-- ---------------------------------------------------------------------------
CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    status       VARCHAR(10) NOT NULL,
    total_amount NUMERIC(30,10) NOT NULL,
    created_at   TIMESTAMP NOT NULL
);

CREATE INDEX idx_orders_status ON orders (status);
-- Deliberately NO index on (user_id, created_at).

-- "Temporary" incident mitigation left behind by the previous DBA.
ALTER TABLE orders SET (
    autovacuum_enabled = off,
    autovacuum_vacuum_scale_factor = 0.8,
    autovacuum_analyze_scale_factor = 0.8
);
-- Defect (g): low statistics target on a skewed column -> planner misestimates.
ALTER TABLE orders ALTER COLUMN status SET STATISTICS 10;

-- ---------------------------------------------------------------------------
-- order_items
-- Defect (b): composite index in the wrong column order for the dominant
--             query pattern (order detail lookups filter by order_id, index
--             leads with product_id); no plain index on order_id at all ->
--             nested-loop pathology when joining orders -> order_items.
-- ---------------------------------------------------------------------------
CREATE TABLE order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT NOT NULL REFERENCES orders (id),
    product_id BIGINT NOT NULL REFERENCES products (id),
    quantity   INTEGER NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL
);

CREATE INDEX idx_order_items_product_order ON order_items (product_id, order_id);
-- Deliberately NO index starting with order_id.

-- ---------------------------------------------------------------------------
-- reviews
-- Defect (e): several redundant/overlapping indexes (write amplification),
--             plus a giant, effectively unused index on review_text.
-- ---------------------------------------------------------------------------
CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL REFERENCES products (id),
    user_id     INTEGER NOT NULL REFERENCES users (id),
    rating      SMALLINT NOT NULL,
    review_text TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL
);

CREATE INDEX idx_reviews_product_id ON reviews (product_id);
CREATE INDEX idx_reviews_product_id_created_at ON reviews (product_id, created_at);
CREATE INDEX idx_reviews_product_id_rating ON reviews (product_id, rating);
CREATE INDEX idx_reviews_review_text ON reviews (review_text);

-- ---------------------------------------------------------------------------
-- payments
-- Defect (i): external_ref is a UUID stored as text, with a btree index used
--             only for equality lookups (bloats under random insert order).
-- Defect (f): autovacuum delayed -> churn phase (status updates) leaves bloat.
-- Defect (h): amount as numeric(30,10); status as varchar(10).
-- ---------------------------------------------------------------------------
CREATE TABLE payments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT NOT NULL REFERENCES orders (id),
    external_ref TEXT NOT NULL,
    amount       NUMERIC(30,10) NOT NULL,
    status       VARCHAR(10) NOT NULL,
    created_at   TIMESTAMP NOT NULL
);

CREATE INDEX idx_payments_order_id ON payments (order_id);
CREATE INDEX idx_payments_external_ref ON payments (external_ref);

ALTER TABLE payments SET (
    autovacuum_enabled = off,
    autovacuum_vacuum_scale_factor = 0.8,
    autovacuum_analyze_scale_factor = 0.8
);

-- ---------------------------------------------------------------------------
-- inventory_events
-- Defect (c): unpartitioned 9M-row time series, all queries filter recent
--             ranges; index bloat from a churn (correction) phase.
-- ---------------------------------------------------------------------------
CREATE TABLE inventory_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL REFERENCES products (id),
    event_type  VARCHAR(20) NOT NULL,
    qty_delta   INTEGER NOT NULL,
    occurred_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_inventory_events_product_id ON inventory_events (product_id);
CREATE INDEX idx_inventory_events_occurred_at ON inventory_events (occurred_at);

ALTER TABLE inventory_events SET (
    autovacuum_enabled = off,
    autovacuum_vacuum_scale_factor = 0.8,
    autovacuum_analyze_scale_factor = 0.8
);
