"""t11 -- feature engineering: the shared fixture every learner and the
validator both import. FULLY IMPLEMENTED -- not a stub, and not the
solution either. The solution is `src/features.py:engineered_features`.

This file provides four things:

  - `SPLIT_SEED` / `TEST_SIZE`: the fixed train/test split parameters.
  - `make_split(df)`: builds the SAME train/test row split every time it is
    called on the full observations DataFrame -- both your own
    experimentation and `tests/validate.py` call this, so you are always
    graded on a held-out set you never got to see features for.
  - `baseline_features(df)`: a WEAK feature set -- columns that barely move
    the needle on price -- used as the "before" picture. Beating it is the
    point of the task.
  - `evaluate(features, df)`: fits one fixed regressor on the training rows
    and reports R^2 on the held-out test rows. Both `baseline_features` and
    your `engineered_features` are scored through this exact same function,
    so the comparison is apples-to-apples.

Do not edit this file. The task is `src/features.py`.

-------------------------------------------------------------------------
Why `discount_pct` / `units_sold` are NOT in the weak baseline
-------------------------------------------------------------------------
An earlier draft of this task used `[seller_rating, discount_pct,
in_stock]` as the "obviously weak" columns. Measuring it turned up a
surprise worth stating explicitly: `discount_pct` (and `units_sold`) are
NOT weak here. This dataset plants a deliberate Simpson's-paradox confound
(see task 09) where `discount_pct` is drawn per-category (toys and apparel
discount heavily, electronics barely at all) -- so `discount_pct` doesn't
cause price, but it correlates with `category`, which very much does. Feed
it to a regressor and it quietly leaks a chunk of the category signal back
in, measured at R^2 ~ 0.24 on its own -- not remotely "weak."

`seller_rating` (iid noise, unrelated to price) and `in_stock` (iid
Bernoulli, unrelated to price) really are weak on their own or combined
(R^2 ~ 0.0). The baseline below uses those plus the raw hour-of-day the
observation was scraped at (also iid with respect to price -- `scraped_at`
plays no role in how price is generated) to give the baseline three
columns without smuggling in a confounded one. This is itself a lesson:
"looks like a plausible price signal" and "actually predicts price" are
different claims, and you only find out which is which by measuring.
"""

import sys
from pathlib import Path

import numpy as np

MODULE_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(MODULE_ROOT))

SPLIT_SEED = 42
TEST_SIZE = 0.2

# A row's price is VALID iff all three hold (same definition used across
# this module's other tasks, e.g. task 02 / task 04): price is not NaN,
# price > 0, currency == "USD". This does NOT catch every data-quality
# defect (a `missing_decimal` row is still a positive, non-NaN, USD price
# -- just wrong by ~100x) -- that is a deliberate, small amount of realistic
# noise in the target, not a bug in this task.


def valid_price_mask(df):
    """Boolean array, length len(df): True where the row's price is usable
    (not NaN, > 0, currency == USD)."""
    return (df["price"].notna() & (df["price"] > 0) & (df["currency"] == "USD")).to_numpy()


def make_split(df):
    """Build the fixed train/test split every learner and the validator
    both use.

    Args:
        df: the full observations DataFrame, e.g.
            `harness.common.load_observations()`. Must NOT be pre-filtered
            -- this function does its own valid-row filtering internally so
            that every caller (your experiments, your feature functions,
            the validator) starts from the same full df and ends up with
            the same split.

    Returns:
        (train_idx, test_idx): two 1-D int arrays of POSITIONAL row indices
        into `df` (i.e. valid for `.iloc[...]` or plain numpy fancy
        indexing on an array built row-aligned with `df`), restricted to
        rows where `valid_price_mask(df)` is True, split via
        `sklearn.model_selection.train_test_split` with
        `test_size=TEST_SIZE, random_state=SPLIT_SEED`.

    Because this always re-derives the valid-row positions from `df` itself
    (rather than caching them), calling it twice on the same `df` -- once
    from your own code, once from `tests/validate.py` -- reproduces
    byte-identical train_idx/test_idx arrays.
    """
    from sklearn.model_selection import train_test_split

    valid_pos = np.flatnonzero(valid_price_mask(df))
    train_idx, test_idx = train_test_split(valid_pos, test_size=TEST_SIZE, random_state=SPLIT_SEED)
    return train_idx, test_idx


def baseline_features(df):
    """The WEAK baseline feature set: `seller_rating`, `in_stock`, and the
    hour-of-day component of `scraped_at`. All three are close to
    independent of `price` by construction (see the module docstring for
    why `discount_pct` -- a tempting fourth choice -- is deliberately
    excluded).

    Args:
        df: the full observations DataFrame (same one passed to
            `make_split`), NOT pre-filtered.

    Returns:
        float64 ndarray, shape (len(df), 3), row-aligned with `df`
        (row i of the output describes row i of `df`). Only the rows
        selected by `make_split`'s train_idx/test_idx are ever actually
        used by `evaluate` -- the other rows' feature values are computed
        but never scored.
    """
    return np.column_stack([
        df["seller_rating"].to_numpy(dtype=float),
        df["in_stock"].to_numpy(dtype=float),
        df["scraped_at"].dt.hour.to_numpy(dtype=float),
    ])


def _to_matrix(features):
    """Normalize `features` (ndarray, DataFrame, or scipy sparse matrix)
    into something that supports row-fancy-indexing and Ridge.fit."""
    import scipy.sparse as sp

    if sp.issparse(features):
        return features.tocsr()
    if hasattr(features, "to_numpy"):
        return features.to_numpy(dtype=float)
    return np.asarray(features, dtype=float)


def evaluate(features, df):
    """Score a feature matrix against `log(price)` on the fixed held-out
    split. This is the SAME function `tests/validate.py` calls on both
    `baseline_features(df)` and your `engineered_features(df)` -- whatever
    gap shows up between the two calls is a fair, apples-to-apples
    comparison.

    Args:
        features: a feature matrix row-aligned with `df` (same row count,
            same row order) -- an ndarray, a pandas DataFrame, or a scipy
            sparse matrix (e.g. the output of a `TfidfVectorizer`).
        df: the full observations DataFrame `features` was derived from.

    Returns:
        float: R^2 of a `sklearn.linear_model.Ridge(alpha=1.0)` regressor,
        fit on the TRAIN split's rows of `features` against
        `log(df["price"])`, scored on the TEST split's rows. Both splits
        come from `make_split(df)`. Features are standardized
        (`StandardScaler`, fit on train only) before fitting, so raw scale
        differences between engineered columns (a 0/1 indicator next to a
        title-length integer next to a TF-IDF weight) don't distort the
        regularization. Ridge has no random component -- calling this
        twice on the same inputs always returns the same number.
    """
    from sklearn.linear_model import Ridge
    from sklearn.metrics import r2_score
    from sklearn.preprocessing import StandardScaler
    import scipy.sparse as sp

    train_idx, test_idx = make_split(df)
    # log() over the FULL price column (including invalid rows: NaN, <= 0)
    # is expected to raise divide-by-zero/invalid warnings that never
    # matter -- only train_idx/test_idx (valid rows only) are ever read
    # back out of y below.
    with np.errstate(divide="ignore", invalid="ignore"):
        y = np.log(df["price"].to_numpy(dtype=float))

    X = _to_matrix(features)
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    scaler = StandardScaler(with_mean=not sp.issparse(X_train))
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    model = Ridge(alpha=1.0)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    return float(r2_score(y_test, preds))
