apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sandbox20-fixture.fullname" . }}
  labels:
    {{- include "sandbox20-fixture.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sandbox20-fixture.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sandbox20-fixture.labels" . | nindent 8 }}
    spec:
      containers:
        - name: sandbox20-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
