apiVersion: v1
kind: Service
metadata:
  name: {{ include "sandbox20-fixture.fullname" . }}
  labels:
    {{- include "sandbox20-fixture.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sandbox20-fixture.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
