"""t01 -- vectorization and broadcasting: the naive, row-by-row reference.

This file is FULLY IMPLEMENTED -- it is not a stub, and it is not the
solution to this task either. It is the "colleague's slow code" the
backstory describes: a plain Python loop over each observation, computing
the same three derived metrics `src/vectorized.py` must reproduce. It
exists so you have (a) a correctness reference to match against and (b) a
slow baseline to beat.

Do not edit this file. The point of the task is `src/vectorized.py`.

All three functions take and return numpy arrays, but none of them use a
numpy operation internally -- every element is visited by an explicit
Python `for` loop, which is exactly what makes them slow: each loop
iteration pays full Python bytecode-interpretation overhead per element,
instead of dropping into a single C loop the way a numpy ufunc would.

Callers are expected to pass already-cleaned input: `prices`/`values` are
finite float64 arrays (no NaN/inf -- filter those out before calling, e.g.
via `np.isfinite`), and `category_codes`/`group_codes` are integer arrays
with no missing/sentinel codes. None of the three functions here handle
NaN or invalid codes -- keeping that concern outside these functions keeps
both this file and `vectorized.py` focused on the actual lesson (loops vs.
broadcasting), not on data cleaning.
"""

import math

import numpy as np

# Trailing window size for rolling_mean, shared with baseline.py and
# tests/validate.py so all three agree on the exact same fixed input.
ROLLING_WINDOW = 30


def zscore_within_category(prices: np.ndarray, category_codes: np.ndarray) -> np.ndarray:
    """Per-element z-score computed WITHIN each category group.

    For every row i, subtracts the mean of prices[j] over all j sharing
    category_codes[i], then divides by the population standard deviation
    (ddof=0) of that same group -- i.e. each group is standardized against
    only its own members, not the whole array.

    Args:
        prices: 1-D float64 array, length n, finite values only.
        category_codes: 1-D integer array, length n, one group code per
            row. Codes may be any hashable integers in any order -- this
            implementation groups by value via a dict, not by position.

    Returns:
        float64 array, length n: out[i] = (prices[i] - mean(group)) /
        std(group, ddof=0), where group = every j with
        category_codes[j] == category_codes[i].

    Assumes every group that appears has a nonzero population std (true
    for every category in this module's dataset, which has thousands of
    rows per category) -- a single-member group would divide by zero,
    which is not handled here.
    """
    n = len(prices)

    sums = {}
    counts = {}
    for i in range(n):
        c = category_codes[i]
        sums[c] = sums.get(c, 0.0) + prices[i]
        counts[c] = counts.get(c, 0) + 1
    means = {c: sums[c] / counts[c] for c in sums}

    sq_devs = {}
    for i in range(n):
        c = category_codes[i]
        d = prices[i] - means[c]
        sq_devs[c] = sq_devs.get(c, 0.0) + d * d
    stds = {c: math.sqrt(sq_devs[c] / counts[c]) for c in sq_devs}

    out = np.empty(n, dtype=np.float64)
    for i in range(n):
        c = category_codes[i]
        out[i] = (prices[i] - means[c]) / stds[c]
    return out


def rolling_mean(values: np.ndarray, window: int) -> np.ndarray:
    """Simple trailing rolling mean.

    For every row i, the mean of values[max(0, i - window + 1) : i + 1] --
    i.e. the mean of the current element and up to `window - 1` preceding
    elements. Near the start of the array (i < window - 1), the window is
    shorter than `window` (it never looks before index 0); this is a
    trailing/expanding-then-fixed window, not a centered one.

    Args:
        values: 1-D float64 array, length n, finite values only.
        window: trailing window size, a positive int.

    Returns:
        float64 array, length n, same semantics as described above.
    """
    n = len(values)
    out = np.empty(n, dtype=np.float64)
    for i in range(n):
        lo = max(0, i - window + 1)
        s = 0.0
        cnt = 0
        for j in range(lo, i + 1):
            s += values[j]
            cnt += 1
        out[i] = s / cnt
    return out


def minmax_scale_per_group(values: np.ndarray, group_codes: np.ndarray) -> np.ndarray:
    """Per-group min-max scaling to [0, 1].

    For every row i, rescales values[i] to (values[i] - min(group)) /
    (max(group) - min(group)), where group = every j with
    group_codes[j] == group_codes[i]. A group whose members are all equal
    (max == min, i.e. a constant group) would divide by zero -- that case
    is special-cased to scale to 0.0 for every member of that group
    instead.

    Args:
        values: 1-D float64 array, length n, finite values only.
        group_codes: 1-D integer array, length n, one group code per row.

    Returns:
        float64 array, length n, every value in [0, 1] (or exactly 0.0 for
        a constant group).
    """
    n = len(values)

    mins = {}
    maxs = {}
    for i in range(n):
        g = group_codes[i]
        v = values[i]
        if g not in mins or v < mins[g]:
            mins[g] = v
        if g not in maxs or v > maxs[g]:
            maxs[g] = v

    out = np.empty(n, dtype=np.float64)
    for i in range(n):
        g = group_codes[i]
        rng = maxs[g] - mins[g]
        out[i] = 0.0 if rng == 0 else (values[i] - mins[g]) / rng
    return out
