name: 'marketplace_analytics'
version: '1.0.0'
config-version: 2

profile: 'marketplace_analytics'

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  marketplace_analytics:
    staging:
      +materialized: view
      +schema: dbt_analytics
    marts:
      +materialized: table
      +schema: dbt_analytics_marts
