"""Shared helpers for module 13 (scraping at scale: a deliberately hostile
local target site, its data-quality/change-detection/selector-resilience/
budget-router pipeline tasks, and Prometheus/Grafana observability of the
whole thing) validators, generators, and task scaffolds.

Every validator prints PASSED or `NOT PASSED: <reason>` and exits 0/1; no
tracebacks reach the learner. Run these host-side via `uv run`. Nothing here
requires a live stack at import time -- httpx and any other third-party
import is lazy inside the functions that actually need them.

There is no shared database in this module -- the target site (Docker,
plain HTTP) is the shared corpus, backed by `data/catalog.json` and
`data/target-spec.json` (both gitignored, regenerated by `generate.py`; only
`data/ground-truth.json` is committed). Parsing/scraping logic is entirely
the learner's own code -- this module deliberately contains NONE.
"""

import json
import os
import sys
import time
import uuid
from pathlib import Path

MODULE_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = MODULE_ROOT / "data"
GROUND_TRUTH_PATH = DATA_DIR / "ground-truth.json"
CATALOG_PATH = DATA_DIR / "catalog.json"
TARGET_SPEC_PATH = DATA_DIR / "target-spec.json"

# Canonical corpus seed -- the single source of truth for generate.py's numpy
# RNG streams. See .authoring/design.md for the full draw-order contract.
SEED = 131313

TARGET_DEFAULT_PORT = 8313
PROM_DEFAULT_PORT = 9313
GRAFANA_DEFAULT_PORT = 3313

# A browser-like default identity for harness/validator requests -- the
# LEARNER writes their own fetch layer for the actual tasks; this is only
# used by validators and harness helpers that need to talk to the target
# without themselves becoming a lesson in header spoofing.
DEFAULT_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)
DEFAULT_ACCEPT_LANGUAGE = "en-US,en;q=0.9"


# --------------------------------------------------------------------------
# Pass / fail plumbing (identical semantics to modules 08/09/10/11/12)
# --------------------------------------------------------------------------

def not_passed(reason):
    print(f"NOT PASSED: {reason}")
    sys.exit(1)


def passed(msg=""):
    print(f"PASSED{': ' + msg if msg else ''}")
    sys.exit(0)


def guarded(fn):
    """Decorator: wrap a validator body so unexpected exceptions become
    NOT PASSED instead of a raw traceback."""
    import functools

    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        try:
            return fn(*args, **kwargs)
        except SystemExit:
            raise
        except NotImplementedError:
            not_passed("scaffold not implemented yet (NotImplementedError)")
        except Exception as e:
            not_passed(f"unexpected error: {type(e).__name__}: {e}")

    return wrapper


def _last_line(text):
    """Last non-empty line of a subprocess stream or error text -- enough to
    say WHY a run failed without leaking a full traceback/stack dump."""
    lines = [ln for ln in (text or "").splitlines() if ln.strip()]
    return lines[-1] if lines else "(no output)"


# --------------------------------------------------------------------------
# Benchmark helpers (relative timing against a machine-local baseline)
# --------------------------------------------------------------------------

def time_it(fn, *args, **kwargs):
    """Call fn(*args, **kwargs), return (result, elapsed_seconds). Wall clock
    via time.perf_counter. Timing checks are always relative to a machine-
    local baseline (see read_baseline / write_baseline), never absolute."""
    start = time.perf_counter()
    result = fn(*args, **kwargs)
    return result, time.perf_counter() - start


def write_baseline(path, obj):
    """Write a machine-local baseline to a gitignored `*-local.json` file.
    Path may be relative to the module root."""
    p = Path(path)
    if not p.is_absolute():
        p = MODULE_ROOT / p
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(obj, indent=2), encoding="utf-8")
    return p


def read_baseline(path):
    """Read a machine-local baseline written by write_baseline, or None if it
    doesn't exist yet (the baseline step hasn't been run)."""
    p = Path(path)
    if not p.is_absolute():
        p = MODULE_ROOT / p
    if not p.exists():
        return None
    return json.loads(p.read_text(encoding="utf-8"))


# --------------------------------------------------------------------------
# Ground truth / corpus data
# --------------------------------------------------------------------------

def load_ground_truth():
    if not GROUND_TRUTH_PATH.exists():
        not_passed(f"ground truth not found at {GROUND_TRUTH_PATH} — run `uv run python generate.py` first")
    return json.loads(GROUND_TRUTH_PATH.read_text(encoding="utf-8"))


def load_catalog():
    if not CATALOG_PATH.exists():
        not_passed(f"catalog not found at {CATALOG_PATH} — run `uv run python generate.py` first")
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))


def load_target_spec():
    if not TARGET_SPEC_PATH.exists():
        not_passed(f"target spec not found at {TARGET_SPEC_PATH} — run `uv run python generate.py` first")
    return json.loads(TARGET_SPEC_PATH.read_text(encoding="utf-8"))


# --------------------------------------------------------------------------
# Ports (env-overridable, module 13 block -- see CONVENTIONS.md)
# --------------------------------------------------------------------------

def target_port():
    return int(os.environ.get("SANDBOX_13_TARGET_PORT", str(TARGET_DEFAULT_PORT)))


def target_base_url():
    return f"http://localhost:{target_port()}"


def prom_port():
    return int(os.environ.get("SANDBOX_13_PROM_PORT", str(PROM_DEFAULT_PORT)))


def prom_base_url():
    return f"http://localhost:{prom_port()}"


def grafana_port():
    return int(os.environ.get("SANDBOX_13_GRAFANA_PORT", str(GRAFANA_DEFAULT_PORT)))


def grafana_base_url():
    return f"http://localhost:{grafana_port()}"


# --------------------------------------------------------------------------
# Target client (validators/harness only -- the learner writes their OWN
# fetch layer for the actual scraping tasks)
# --------------------------------------------------------------------------

class TargetClient:
    """Thin httpx.Client wrapper against the target site: sets a browser-like
    default User-Agent/Accept-Language (so it passes the header gate out of
    the box) and a per-instance X-Client-Id (random uuid4 unless given).
    Intentionally minimal -- no retry/backoff/rate-limit awareness, no
    parsing. That is the learner's job in the actual tasks; this exists so
    validators/harness scripts can poke the target without duplicating a
    scraping stack."""

    def __init__(self, client_id=None, base_url=None, headers=None, **httpx_kwargs):
        import httpx

        self.client_id = client_id or str(uuid.uuid4())
        self.base_url = base_url or target_base_url()
        merged_headers = {
            "User-Agent": DEFAULT_USER_AGENT,
            "Accept-Language": DEFAULT_ACCEPT_LANGUAGE,
            "X-Client-Id": self.client_id,
        }
        if headers:
            merged_headers.update(headers)
        self._client = httpx.Client(base_url=self.base_url, headers=merged_headers, **httpx_kwargs)

    def get(self, path, **kwargs):
        return self._client.get(path, **kwargs)

    def close(self):
        self._client.close()

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()


def get_client_state(client_id, base_url=None):
    """GET /__debug/client for `client_id` -> parsed JSON dict, or NOT PASSED
    if the target is unreachable."""
    import httpx

    url = (base_url or target_base_url()) + "/__debug/client"
    try:
        resp = httpx.get(url, headers={"X-Client-Id": client_id}, timeout=5.0)
        resp.raise_for_status()
        return resp.json()
    except httpx.HTTPError as e:
        not_passed(f"could not reach target /__debug/client on {target_port()}: {e}")


def reset_client(client_id, base_url=None):
    """POST /__debug/reset for `client_id`, or NOT PASSED if unreachable."""
    import httpx

    url = (base_url or target_base_url()) + "/__debug/reset"
    try:
        resp = httpx.post(url, headers={"X-Client-Id": client_id}, timeout=5.0)
        resp.raise_for_status()
        return resp.json()
    except httpx.HTTPError as e:
        not_passed(f"could not reach target /__debug/reset on {target_port()}: {e}")


# --------------------------------------------------------------------------
# Prometheus (task 06's optional live check -- callers decide skip vs fail)
# --------------------------------------------------------------------------

def query_prometheus(expr, base_url=None):
    """GET /api/v1/query?query=<expr> against Prometheus -> parsed JSON body,
    or None if Prometheus is unreachable. Raises no exception on connection
    failure (returns None instead) so a caller can decide "skip this check"
    vs "fail" -- Prometheus/Grafana live checks are always skip-if-down in
    this module, never a hard requirement for a task's core pass/fail."""
    import httpx

    url = (base_url or prom_base_url()) + "/api/v1/query"
    try:
        resp = httpx.get(url, params={"query": expr}, timeout=5.0)
        resp.raise_for_status()
        return resp.json()
    except httpx.HTTPError:
        return None
