"""04 -- embedding-dedup: group duplicate product listings via a local
embedding model + cosine similarity, where exact/fuzzy string matching
fails.

The input is a list of product title VARIANTS -- some titles describing
the same underlying product were generated by reordering tokens,
abbreviating a word, swapping punctuation, or moving the brand to a
different position in the string. Others describing genuinely different
products may still share a brand or an adjective. Neither an exact string
match nor a naive edit-distance/fuzzy match reliably separates the two
cases (e.g. "Compact" vs "Cpt" is a semantic abbreviation, not a small
edit distance; "Voltix Compact earbuds A123" vs "Compact earbuds A123
(Voltix)" is a token reorder with punctuation added). An embedding model
maps semantically similar titles to nearby vectors regardless of surface
form, which is what makes cosine similarity over embeddings work here
where string matching does not.
"""


def cluster_items(items: list[dict], client) -> dict:
    """Cluster near-duplicate product listings by title similarity.

    Args:
        items: list of {"item_id": str, "title": str} dicts -- title
            variants of possibly-different underlying products. Multiple
            items may describe the SAME product (title differs by token
            order, abbreviation, punctuation, or brand position) or may
            describe DIFFERENT products (which can still share tokens,
            e.g. the same brand or adjective on a different noun).
        client: an `harness.llm.LLMClient` (see `harness/llm.py`), already
            constructed and ready to use. Call `client.embed(texts:
            list[str]) -> list[list[float]]` to get one embedding vector
            per input text, in the same order as the input list. Do not
            construct a client yourself inside this function -- the caller
            owns that, so a validator/test can inject a shared instance.

    Returns:
        dict mapping every `item["item_id"]` in `items` to a cluster
        label. Label VALUES are arbitrary (str, int, whatever your
        clustering method naturally produces) -- only the PARTITION of
        item_ids into groups matters: two item_ids assigned the same label
        are asserted to describe the same underlying product, two item_ids
        assigned different labels are asserted to describe different
        products. Every item_id in the input must appear as a key in the
        returned dict.

    Suggested approach (not required -- any method that reads
    `client.embed` and produces a valid partition of the input is fine):

      1. Embed every title in one batch:
         `vecs = client.embed([it["title"] for it in items])`.
      2. Compute pairwise cosine similarity between every pair of vectors
         (`harness.llm.cosine` for a single pair, or a vectorized
         numpy dot-product over L2-normalized vectors for all pairs at
         once).
      3. Pick a similarity threshold and connect any pair at or above it
         (union-find / connected components over the resulting graph), OR
         use an off-the-shelf clustering method (e.g.
         `sklearn.cluster.AgglomerativeClustering` with a cosine-distance
         threshold, if you'd rather not hand-roll union-find) -- your
         choice of method and threshold.
      4. Assign every connected component / cluster a distinct label and
         return the item_id -> label mapping.

    Two degenerate partitions are both invalid solutions here, for
    opposite reasons: putting every item in its own cluster has perfect
    precision but recall collapses to zero on every real duplicate pair;
    putting every item in one giant cluster has perfect recall but
    precision collapses under all the true negative pairs it wrongly
    merges. A real clustering has to thread between the two.
    """
    raise NotImplementedError
