"""Window functions over PriceWatch's price-snapshot events, at a scale where
the naive approach falls over.

PriceWatch wants two leaderboards:
  - the top-N offers per source (a per-source leaderboard by price), and
  - per-product price movement over time (latest price vs. the previous
    snapshot).

Both are naturally window questions: "rank within a group" and "compare a
row to another row in the same group's ordering." At 2M rows this is
comfortable no matter how you write it. At 50M+ rows, with source_id 1
holding roughly 30% of all traffic, the difference between a window whose
partitionBy key is that skewed and a pre-aggregated equivalent stops being
academic — one huge partition has to be sorted end to end by a single task
while the other 19 finish in a fraction of the time.

Raw JSONL rows have a top-level `_corrupt_record` column when a line fails
to parse as JSON — "drop unparseable lines" always means
`filter(col("_corrupt_record").isNull())`.

"Deduplicate" always means whole-row `.distinct()` on the parsed events
(after dropping `_corrupt_record`), removing the retry-storm repeats
injected during generation.
"""

from pathlib import Path


def prepare_events(spark, jsonl_dir: Path):
    """Build the shared input DataFrame every function below starts from.

    Read every *.jsonl file under jsonl_dir, then:
      1. Drop rows where the JSON failed to parse (`_corrupt_record` is not
         null) and drop the `_corrupt_record` column itself.
      2. Deduplicate exact retry-storm repeats: whole-row `.distinct()`.
      3. Do NOT filter on `http_status` here. Unlike task 04's
         prepare_events, this one deliberately keeps failed-scrape rows
         (http_status != 200, price/in_stock null) in the output — each
         function below applies whatever status filter it actually needs,
         since some window questions in this module might reasonably want
         to reason about failed scrapes and it's each function's job to be
         explicit about what it filters, not this shared one's.
      4. Select exactly the columns everything below needs:
         `product_id`, `source_id`, `price`, `http_status`, `captured_at`.

    Returns:
        a DataFrame with columns (product_id, source_id, price, http_status,
        captured_at). `captured_at` stays as the original ISO-8601 string
        column — it sorts correctly as a string because the format is
        fixed-width and zero-padded, so no timestamp cast is required for
        any ordering in this task, though you're free to cast it if you
        prefer.
    """
    raise NotImplementedError("implement prepare_events")


def top_n_per_source(spark, events_df, n: int = 3):
    """Top n offers per source_id, ranked by price, http_status==200 rows only.

    This is the leaderboard PriceWatch's product managers want: "for each
    source, what are its n highest-priced live offers right now, and in
    what order?"

    Contract, matched exactly against `ground-truth.json`'s
    `top_n_per_source.by_source`:
      - Filter to `http_status == 200` first (price is only meaningful on a
        successful scrape).
      - Order by `price` descending, breaking ties by `product_id`
        descending — this is a total order over (price, product_id), so
        "ties" only ever occur when both columns are equal (the same
        product recorded at the same price on two different snapshots,
        which whole-row `.distinct()` does not collapse since the rows
        differ in `captured_at` or other columns).
      - Take the first n rows of that order, per source_id.

    You must use a window function here (partitionBy("source_id"),
    orderBy(desc("price"), desc("product_id"))) — the validator inspects
    the plan and requires a `Window` node. The one thing worth getting
    right before you write any code: which ranking function.

    `row_number()`, `rank()`, and `dense_rank()` all answer different
    questions once there's a tie on the full (price, product_id) order key,
    and only one of them reproduces `ground-truth.json` exactly:
      - `ground-truth.json` was generated by literally sorting each
        source's deduplicated http_status==200 rows by (price desc,
        product_id desc) and slicing the first n — every row counts once
        toward that slice, tied or not, and the slice always has exactly n
        entries (as long as the source has >= n rows at all).
      - `rank()` and `dense_rank()` both let every row tied for a boundary
        position "through" — if 3 rows are tied for the #3 spot, a
        `rank() <= 3` filter returns more than 3 rows for that source. That
        does not match `ground-truth.json`, which always caps at exactly n.
      - `row_number()` assigns strictly increasing integers even to tied
        rows, so `row_number() <= n` always returns exactly n rows per
        source (given >= n rows to begin with) — this is what
        `ground-truth.json`'s slicing actually does, and it's the function
        that reproduces the ground truth exactly, including sources where
        the same product_id appears twice in the top n at two different
        prices (that's not a tie at all, just two distinct top-n rows for
        the same product — verify this against a source's list in
        `ground-truth.json` before you trust your output).

    Returns:
        a DataFrame with columns (source_id, product_id, price, rn), one
        row per (source_id, rn) pair for rn in [1, n], where rn=1 is that
        source's single highest-priced offer. Do not filter to distinct
        product_id — the same product may legitimately appear more than
        once in one source's top n at different prices.
    """
    raise NotImplementedError("implement top_n_per_source")


def price_change_per_product(spark, events_df):
    """Per-product latest price vs. its previous snapshot, via lag().

    PriceWatch's other leaderboard: "for every product, what did its price
    just do?" Build this with `lag()` over
    `partitionBy("product_id").orderBy("captured_at")` on http_status==200
    rows (price is only meaningful when the scrape succeeded):

      1. Filter events_df to http_status == 200.
      2. `prev_price = lag("price").over(w)` and
         `prev_captured_at = lag("captured_at").over(w)`, where `w` is
         partitioned by product_id and ordered by captured_at ascending —
         this gives every row the price and timestamp of the *previous*
         observation for that same product, or null if it's the product's
         first observation.
      3. Keep only the last observation per product (the one with the
         maximum captured_at in its partition) — that row's `price` is the
         product's current/latest price, and its `prev_price` /
         `prev_captured_at` (computed in step 2, before this filter) are
         exactly the previous snapshot's values.
      4. Compute `price_delta = price - prev_price` (null propagates
         naturally when prev_price is null, i.e. a product with only one
         valid observation).

    This dataset's captured_at timestamps are effectively unique per
    product among http_status==200 rows (verify this assumption on your
    own machine — two valid snapshots of the same product at the exact
    same second would make "the previous row" ambiguous, and both this
    function and the validator's independent reference need to agree on
    which row that is).

    The validator does not compare this function's output to
    `ground-truth.json` (there is no lag-based aggregate in it) — instead
    it builds its own reference for the same quantity using only
    `groupBy`/`join` (no window function at all) and checks that your
    window-based answer and its groupBy/join answer agree on every
    product. That agreement, not a fixed expected value, is the point:
    a window and a hand-rolled "find the max, then find the max of what's
    left" pipeline are two ways of computing the same thing, and they had
    better produce the same numbers.

    Returns:
        a DataFrame with columns (product_id, latest_price,
        latest_captured_at, prev_price, prev_captured_at, price_delta),
        one row per product_id that has at least one http_status==200
        observation. prev_price/prev_captured_at/price_delta are null for
        a product with exactly one valid observation.
    """
    raise NotImplementedError("implement price_change_per_product")


def window_vs_aggregate_plans(spark, events_df):
    """Same question, two shapes: what is the highest-priced http_status==200
    offer in each source, and what does each shape cost in plan terms?

    Compute "max price per source_id, http_status==200 rows only" two
    independent ways:

      1. Windowed: `row_number()` over `partitionBy("source_id")
         .orderBy(desc("price"), desc("product_id"))`, filtered to rn == 1.
         This is the n=1 case of `top_n_per_source` — every row in the
         source's partition has to be sorted by the window (all of it, not
         just the winner), which for source_id 1 (~30% of all traffic)
         means one task sorting a partition roughly 30 times the size of
         an average one.
      2. Pre-aggregated: `groupBy("source_id").agg(max("price"))`. Catalyst
         can partially aggregate this *before* any shuffle (a local max per
         input partition, then a shuffle of only 20 partial-max rows per
         input partition to combine) — nothing here requires sorting a
         whole partition by price, just tracking a running max.

    Capture both plans with `harness.common.get_plan` before or after
    materializing (either is fine, the validator only inspects the plan
    text and the two per-source-max results). Do not call `.limit(n)` /
    filter to top-1 differently between the two — both must answer exactly
    "max price per source," so their results should agree with each other
    and with `ground-truth.json`'s `top_n_per_source.by_source[source][0]`
    (the first entry in each source's list is already that source's
    maximum price).

    Returns:
        {
            "window_plan": str,
            "aggregate_plan": str,
            "window_max_price_by_source": {source_id: price, ...},
            "aggregate_max_price_by_source": {source_id: price, ...},
        }
        both price dicts covering all source_ids present in events_df,
        keyed by source_id as a string.
    """
    raise NotImplementedError("implement window_vs_aggregate_plans")
