// CP1 — contracts + api agree.
//
// GIVEN. Do not edit this file — see the capstone README.
//
// Two things are checked, at two different phases:
//
//   - At typecheck time (`pnpm --filter @t3/e2e run typecheck`): the type-
//     level assertions below, comparing @t3/api's ApiHandlers surface
//     against @t3/contracts types, plus hand-pinned literal shapes for the
//     contracts themselves, plus a handful of @ts-expect-error reject
//     cases.
//   - At test time (`pnpm --filter @t3/e2e run test -- cp1`): a live
//     `startMockServer()` seeded deterministically (seed 0xc0ffee, the
//     harness's default), driving @t3/api's handlers and comparing results
//     against values hand-computed independently of any learner code (see
//     `.authoring/notes-t03.md` if you're reading this after finishing —
//     never re-derived by calling the handlers a second way).

import { afterAll, beforeAll, describe, expect, test } from "vitest";
import { startMockServer, type MockServer, type Expect, type Equal } from "@sandbox19/harness";
import { ApiRequestError, createApiHandlers, type ApiHandlers } from "@t3/api";
import type {
  CategorySummary,
  ListProductsParams,
  Product,
  ProductPage,
  SearchResult,
} from "@t3/contracts";

// ============================================================================
// Type-level: @t3/api's handler surface must be EXPRESSED IN @t3/contracts
// types (imported, not a redeclared look-alike). If @t3/api ever stops
// importing from @t3/contracts — or @t3/contracts changes and @t3/api
// doesn't follow — these structural comparisons stop holding.
// ============================================================================

type _GetProductIsContractTyped = Expect<
  Equal<ApiHandlers["getProduct"], (id: number) => Promise<Product>>
>;
type _ListProductsIsContractTyped = Expect<
  Equal<ApiHandlers["listProducts"], (params: ListProductsParams) => Promise<ProductPage>>
>;
type _CategorySummaryIsContractTyped = Expect<
  Equal<ApiHandlers["getCategorySummary"], (categoryId: number) => Promise<CategorySummary>>
>;
type _SearchProductsIsContractTyped = Expect<
  Equal<ApiHandlers["searchProducts"], (q: string) => Promise<SearchResult>>
>;

// ============================================================================
// Type-level: the contracts themselves must have exactly this shape —
// pinned by hand here, independent of whatever @t3/api or @t3/web happen to
// do with them, so a contracts-only mistake is caught even if every
// consumer "agrees" with a wrong shape.
// ============================================================================

type ExpectedProduct = {
  id: number;
  sku: string;
  name: string;
  categoryId: number;
  sellerId: number;
  price: number;
  inStock: boolean;
  scrapedAt: string;
};
type _ProductShape = Expect<Equal<Product, ExpectedProduct>>;

type ExpectedProductPage = { items: Product[]; nextCursor: string | null };
type _ProductPageShape = Expect<Equal<ProductPage, ExpectedProductPage>>;

type ExpectedListProductsParams = { cursor?: string | undefined; limit?: number | undefined };
type _ListProductsParamsShape = Expect<Equal<ListProductsParams, ExpectedListProductsParams>>;

type ExpectedCategorySummary = {
  categoryId: number;
  productCount: number;
  avgPrice: number;
  inStockCount: number;
};
type _CategorySummaryShape = Expect<Equal<CategorySummary, ExpectedCategorySummary>>;

type ExpectedSearchResult = { items: Product[] };
type _SearchResultShape = Expect<Equal<SearchResult, ExpectedSearchResult>>;

// ============================================================================
// Type-level reject cases: ApiHandlers must actually restrict its inputs.
// An over-permissive stub makes one of these lines compile, which surfaces
// as an "unused @ts-expect-error" compile error — itself a clean signal.
// ============================================================================

function _typeRejectCases(handlers: ApiHandlers): void {
  // @ts-expect-error id must be a number, not a numeric string
  void handlers.getProduct("1");

  // @ts-expect-error cursor must be a string, not a number
  void handlers.listProducts({ cursor: 123 });

  // @ts-expect-error q must be a string, not a number
  void handlers.searchProducts(42);
}

// ============================================================================
// Runtime: a live mock server, seeded deterministically, driving @t3/api.
// ============================================================================

describe("CP1 — contracts + api agree", () => {
  let server: MockServer;
  let handlers: ApiHandlers;

  beforeAll(async () => {
    server = await startMockServer(); // default seed 0xc0ffee
    handlers = createApiHandlers(server.baseUrl);
  });

  afterAll(async () => {
    await server.close();
  });

  test("getProduct(1) returns the known seed(0xc0ffee) product", async () => {
    const product = await handlers.getProduct(1);
    expect(product, "getProduct(1) must match the hand-pinned seed(0xc0ffee) fixture").toEqual({
      id: 1,
      sku: "SKU-00001",
      name: "Rustic Apparatus 1",
      categoryId: 7,
      sellerId: 9,
      price: 107.84,
      inStock: true,
      scrapedAt: "2024-01-01T01:00:00.000Z",
    });
  });

  test("getProduct(42) returns the known seed(0xc0ffee) product", async () => {
    const product = await handlers.getProduct(42);
    expect(product, "getProduct(42) must match the hand-pinned seed(0xc0ffee) fixture").toEqual({
      id: 42,
      sku: "SKU-00042",
      name: "Vintage Doohickey 42",
      categoryId: 1,
      sellerId: 12,
      price: 48.34,
      inStock: true,
      scrapedAt: "2024-01-02T18:00:00.000Z",
    });
  });

  test("getProduct(9999) rejects with a typed ApiRequestError, not a bare throw", async () => {
    await expect(
      handlers.getProduct(9999),
      "an unknown product id must reject the promise, not resolve to garbage",
    ).rejects.toBeInstanceOf(ApiRequestError);

    try {
      await handlers.getProduct(9999);
      expect.fail("getProduct(9999) should have thrown before reaching this line");
    } catch (err) {
      expect(err, "the thrown error must be an ApiRequestError instance").toBeInstanceOf(
        ApiRequestError,
      );
      const apiErr = err as ApiRequestError;
      expect(apiErr.status, "the mock server returns HTTP 404 for an unknown product id").toBe(
        404,
      );
      expect(
        apiErr.apiError,
        "the wrapped body must parse against ApiErrorSchema and carry code 'not_found'",
      ).toEqual({ error: { code: "not_found", message: "no product 9999" } });
    }
  });

  test("listProducts({ limit: 3 }) returns the known first page", async () => {
    const page = await handlers.listProducts({ limit: 3 });
    expect(page, "first page (limit 3) must match the hand-pinned seed(0xc0ffee) fixture").toEqual(
      {
        items: [
          {
            id: 1,
            sku: "SKU-00001",
            name: "Rustic Apparatus 1",
            categoryId: 7,
            sellerId: 9,
            price: 107.84,
            inStock: true,
            scrapedAt: "2024-01-01T01:00:00.000Z",
          },
          {
            id: 2,
            sku: "SKU-00002",
            name: "Sleek Sprocket 2",
            categoryId: 7,
            sellerId: 4,
            price: 395.31,
            inStock: false,
            scrapedAt: "2024-01-01T02:00:00.000Z",
          },
          {
            id: 3,
            sku: "SKU-00003",
            name: "Modular Contraption 3",
            categoryId: 2,
            sellerId: 5,
            price: 513.47,
            inStock: true,
            scrapedAt: "2024-01-01T03:00:00.000Z",
          },
        ],
        nextCursor: "aWQ6Mw",
      },
    );
  });

  test("listProducts with the previous page's cursor continues where it left off", async () => {
    const page = await handlers.listProducts({ cursor: "aWQ6Mw", limit: 5 });
    const first = page.items[0];
    expect(first, "the continued page must not be empty").toBeDefined();
    expect(first?.id, "the continued page must start right after id 3").toBe(4);
    expect(
      page.items.map((p) => p.id),
      "the continued page must contain exactly ids 4..8, in order",
    ).toEqual([4, 5, 6, 7, 8]);
    expect(
      page.nextCursor,
      "there are more than 8 products total, so nextCursor must not be null",
    ).not.toBeNull();
  });

  test("getCategorySummary(1) returns the known aggregate", async () => {
    const summary = await handlers.getCategorySummary(1);
    expect(
      summary,
      "category 1's summary must match the hand-pinned seed(0xc0ffee) fixture",
    ).toEqual({
      categoryId: 1,
      productCount: 27,
      avgPrice: 416.19,
      inStockCount: 25,
    });
  });

  test("searchProducts('widget') returns the known result set", async () => {
    const result = await handlers.searchProducts("widget");
    expect(result.items, "searching 'widget' must return exactly 23 known matches").toHaveLength(
      23,
    );
    expect(
      result.items.slice(0, 3),
      "the first 3 matches (ascending by id) must match the hand-pinned fixture",
    ).toEqual([
      {
        id: 5,
        sku: "SKU-00005",
        name: "Portable Widget 5",
        categoryId: 6,
        sellerId: 4,
        price: 242.82,
        inStock: true,
        scrapedAt: "2024-01-01T05:00:00.000Z",
      },
      {
        id: 7,
        sku: "SKU-00007",
        name: "Deluxe Widget 7",
        categoryId: 6,
        sellerId: 7,
        price: 273,
        inStock: true,
        scrapedAt: "2024-01-01T07:00:00.000Z",
      },
      {
        id: 19,
        sku: "SKU-00019",
        name: "Deluxe Widget 19",
        categoryId: 1,
        sellerId: 8,
        price: 623.03,
        inStock: true,
        scrapedAt: "2024-01-01T19:00:00.000Z",
      },
    ]);
  });
});
