// CP2 — worker round-trip.
//
// GIVEN. Do not edit this file — see the capstone README.
//
// A contract-typed job message serializes (JSON round-trip, the same as it
// would over a real queue) -> @t3/worker's `receiveJobMessage` validates it
// -> `processJob` produces a contract-valid result. Malformed and unknown-
// version envelopes must be REJECTED via the contract's discriminated
// union as a typed `{ ok: false, error }`, never a thrown exception.
//
// The anti-drift lever for this checkpoint lives in @t3/worker itself, not
// here: `processJob` must be an EXHAUSTIVE switch over `job.kind` with a
// `default` branch calling an `assertNever` helper. Adding or renaming a
// kind in @t3/contracts without updating that switch breaks
// `pnpm --filter @t3/worker run typecheck` at that line — this file can't
// exercise that directly (it's a property of a *different* package's
// typecheck), but the hand-pinned type shapes below break the moment
// @t3/contracts' job types stop matching this checkpoint's expectations.

import { describe, expect, test } from "vitest";
import type { Expect, Equal } from "@sandbox19/harness";
import { processJob, receiveJobMessage, type ReceiveResult } from "@t3/worker";
import { JobResultSchema, type JobError, type JobKind, type JobMessage, type JobResult } from "@t3/contracts";

// ============================================================================
// Type-level: hand-pinned shapes for the job envelope and its result. These
// fail on stock (contracts' placeholders are `unknown`) and must hold once
// @t3/contracts is filled in for real.
// ============================================================================

type _JobKindPin = Expect<Equal<JobKind, "product.enrich" | "product.reprice">>;

type ExpectedJobMessage =
  | {
      kind: "product.enrich";
      version: 1;
      jobId: string;
      payload: { productId: number; sku: string; price: number };
    }
  | {
      kind: "product.reprice";
      version: 1;
      jobId: string;
      payload: { productId: number; currentPrice: number; adjustmentPct: number };
    };
type _JobMessageShape = Expect<Equal<JobMessage, ExpectedJobMessage>>;

type ExpectedJobResult =
  | {
      kind: "product.enrich";
      jobId: string;
      result: { productId: number; normalizedSku: string; priceTier: "budget" | "standard" | "premium" };
    }
  | { kind: "product.reprice"; jobId: string; result: { productId: number; newPrice: number } };
type _JobResultShape = Expect<Equal<JobResult, ExpectedJobResult>>;

type ExpectedJobError = { jobId: string | null; reason: string };
type _JobErrorShape = Expect<Equal<JobError, ExpectedJobError>>;

function _typeRejectCases(receive: (raw: unknown) => ReceiveResult): void {
  const result = receive({});
  if (result.ok) {
    // @ts-expect-error a valid job's `kind` can never be an unrelated string literal
    const _bad: "not-a-real-kind" = result.job.kind;
    void _bad;
  }
}

// ============================================================================
// Runtime: serialize -> receive -> process, plus rejection paths.
// ============================================================================

describe("CP2 — worker round-trip", () => {
  test("a valid product.enrich v1 envelope round-trips through JSON and produces the expected result", () => {
    const job = {
      kind: "product.enrich",
      version: 1,
      jobId: "job-enrich-1",
      payload: { productId: 42, sku: " sku-00042 ", price: 48.34 },
    };
    // Simulate arriving off a queue: serialize, then deserialize into `unknown`.
    const raw: unknown = JSON.parse(JSON.stringify(job));

    const received = receiveJobMessage(raw);
    expect(received.ok, "a well-formed, correctly-versioned envelope must be accepted").toBe(true);
    if (!received.ok) throw new Error("unreachable: asserted received.ok above");

    const result = processJob(received.job);
    const validated = JobResultSchema.parse(result);
    expect(validated, "the produced result must itself parse against JobResultSchema").toEqual({
      kind: "product.enrich",
      jobId: "job-enrich-1",
      result: { productId: 42, normalizedSku: "SKU-00042", priceTier: "budget" },
    });
  });

  test("priceTier classifies standard and premium correctly at the boundaries", () => {
    const standard = receiveJobMessage({
      kind: "product.enrich",
      version: 1,
      jobId: "job-enrich-2",
      payload: { productId: 7, sku: "SKU-00007", price: 273 },
    });
    expect(standard.ok, "job-enrich-2 is well-formed and must be accepted").toBe(true);
    if (!standard.ok) throw new Error("unreachable");
    expect(
      JobResultSchema.parse(processJob(standard.job)),
      "price 273 is in [50, 500) -> standard",
    ).toEqual({
      kind: "product.enrich",
      jobId: "job-enrich-2",
      result: { productId: 7, normalizedSku: "SKU-00007", priceTier: "standard" },
    });

    const premium = receiveJobMessage({
      kind: "product.enrich",
      version: 1,
      jobId: "job-enrich-3",
      payload: { productId: 3, sku: "SKU-00003", price: 513.47 },
    });
    expect(premium.ok, "job-enrich-3 is well-formed and must be accepted").toBe(true);
    if (!premium.ok) throw new Error("unreachable");
    expect(
      JobResultSchema.parse(processJob(premium.job)),
      "price 513.47 is >= 500 -> premium",
    ).toEqual({
      kind: "product.enrich",
      jobId: "job-enrich-3",
      result: { productId: 3, normalizedSku: "SKU-00003", priceTier: "premium" },
    });
  });

  test("a valid product.reprice v1 envelope produces the expected rounded result", () => {
    const raw: unknown = JSON.parse(
      JSON.stringify({
        kind: "product.reprice",
        version: 1,
        jobId: "job-reprice-1",
        payload: { productId: 1, currentPrice: 200, adjustmentPct: -15 },
      }),
    );

    const received = receiveJobMessage(raw);
    expect(received.ok, "a well-formed, correctly-versioned envelope must be accepted").toBe(true);
    if (!received.ok) throw new Error("unreachable: asserted received.ok above");

    const validated = JobResultSchema.parse(processJob(received.job));
    expect(validated, "200 * (1 - 0.15) = 170").toEqual({
      kind: "product.reprice",
      jobId: "job-reprice-1",
      result: { productId: 1, newPrice: 170 },
    });
  });

  test("product.reprice rounds to exactly 2 decimal places", () => {
    const received = receiveJobMessage({
      kind: "product.reprice",
      version: 1,
      jobId: "job-reprice-2",
      payload: { productId: 5, currentPrice: 49.99, adjustmentPct: 20 },
    });
    expect(received.ok, "job-reprice-2 is well-formed and must be accepted").toBe(true);
    if (!received.ok) throw new Error("unreachable");
    const validated = JobResultSchema.parse(processJob(received.job));
    expect(
      validated,
      "49.99 * 1.2 = 59.988, rounded to 2 decimal places is 59.99 (not 59.988 or 60)",
    ).toEqual({
      kind: "product.reprice",
      jobId: "job-reprice-2",
      result: { productId: 5, newPrice: 59.99 },
    });
  });

  test("an unknown job kind is rejected as a typed error, not a crash", () => {
    expect(
      () => receiveJobMessage({ kind: "product.delete", version: 1, jobId: "j1", payload: {} }),
      "receiveJobMessage must never throw synchronously, even for an unrecognized kind",
    ).not.toThrow();

    const result = receiveJobMessage({
      kind: "product.delete",
      version: 1,
      jobId: "j1",
      payload: {},
    });
    expect(result.ok, "an unrecognized kind must be rejected").toBe(false);
    if (result.ok) throw new Error("unreachable: asserted !result.ok above");
    expect(typeof result.error.reason, "the rejection must carry a human-readable reason").toBe(
      "string",
    );
    expect(
      result.error.reason.length > 0,
      "the rejection reason must not be an empty string",
    ).toBe(true);
    expect(
      result.error.jobId,
      "jobId is recoverable here because raw.jobId was a string, even though the envelope as a whole is invalid",
    ).toBe("j1");
  });

  test("a known kind with an unknown version is rejected as a typed error", () => {
    const result = receiveJobMessage({
      kind: "product.enrich",
      version: 2,
      jobId: "j2",
      payload: { productId: 1, sku: "x", price: 1 },
    });
    expect(result.ok, "version 2 does not exist yet; this must be rejected, not silently accepted").toBe(
      false,
    );
    if (result.ok) throw new Error("unreachable: asserted !result.ok above");
    expect(result.error.jobId, "jobId is recoverable from the raw payload").toBe("j2");
  });

  test("a malformed payload for a known kind/version is rejected as a typed error", () => {
    const result = receiveJobMessage({
      kind: "product.enrich",
      version: 1,
      jobId: "j3",
      payload: { productId: "not-a-number", sku: 5, price: "cheap" },
    });
    expect(result.ok, "wrong field types inside payload must fail validation").toBe(false);
    if (result.ok) throw new Error("unreachable: asserted !result.ok above");
    expect(result.error.jobId, "jobId is recoverable from the raw payload").toBe("j3");
  });

  test.each([null, "just a string", 42, [], undefined])(
    "a non-envelope raw value (%j) is rejected with jobId: null, not a crash",
    (raw) => {
      expect(() => receiveJobMessage(raw), "must never throw synchronously").not.toThrow();
      const result = receiveJobMessage(raw);
      expect(result.ok, "a non-envelope value can never be a valid job message").toBe(false);
      if (result.ok) throw new Error("unreachable: asserted !result.ok above");
      expect(
        result.error.jobId,
        "there is no object to recover a jobId from, so it must be null",
      ).toBeNull();
    },
  );
});
