// CP3 — web client end-to-end, plus the DESIGN.md gate.
//
// GIVEN. Do not edit this file — see the capstone README.
//
// Two independent things are checked here:
//
//   1. @t3/web's typed client, wired directly to @t3/api's handlers (no
//      @t3/api dependency in @t3/web's package.json — see @t3/web's
//      client.ts for why that's possible), consuming real responses from a
//      live, deterministically-seeded mock server. Then, separately, a
//      FAKE port that returns a malformed value cast past the type system
//      — @t3/web must still catch it at runtime and throw, never pass it
//      through. This is the anti-cast check, same spirit as the SDK task's
//      malformed-route rule.
//   2. `../../../DESIGN.md` (this capstone's root) is read and checked for
//      five filled-in sections. This gate is independent of the two
//      TypeScript packages above — CP1/CP2 can pass while this still
//      fails, and vice versa.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, test } from "vitest";
import { startMockServer, type MockServer } from "@sandbox19/harness";
import { createApiHandlers, type ApiHandlers } from "@t3/api";
import { createWebClient, type ProductsPort, type WebClient } from "@t3/web";
import type { Product } from "@t3/contracts";

describe("CP3 — web client end-to-end", () => {
  let server: MockServer;
  let api: ApiHandlers;
  let web: WebClient;

  beforeAll(async () => {
    server = await startMockServer(); // default seed 0xc0ffee
    api = createApiHandlers(server.baseUrl);
    // `api` is not declared as a ProductsPort anywhere — it satisfies the
    // port structurally, purely because both sides are typed off
    // @t3/contracts. That's the point: no @t3/web -> @t3/api dependency
    // edge exists in package.json, only a shared-contract one.
    web = createWebClient(api);
  });

  afterAll(async () => {
    await server.close();
  });

  test("web.getProduct(1) round-trips through api and matches the known seed(0xc0ffee) product", async () => {
    const product = await web.getProduct(1);
    expect(
      product,
      "web's client must return the same contract-valid product api itself would",
    ).toEqual({
      id: 1,
      sku: "SKU-00001",
      name: "Rustic Apparatus 1",
      categoryId: 7,
      sellerId: 9,
      price: 107.84,
      inStock: true,
      scrapedAt: "2024-01-01T01:00:00.000Z",
    });
  });

  test("web.listProducts({ limit: 3 }) round-trips through api and matches the known first page", async () => {
    const page = await web.listProducts({ limit: 3 });
    expect(
      page.items.map((p) => p.id),
      "the first page (limit 3) must contain exactly ids 1, 2, 3, in order",
    ).toEqual([1, 2, 3]);
    expect(page.nextCursor, "the known seed's page-3 cursor").toBe("aWQ6Mw");
  });

  test("a malformed value from the port is caught and rejected, never silently cast through", async () => {
    const fakePort: ProductsPort = {
      // Deliberately lies about its return type via `as` — the same shape
      // of lie a naive `return (await res.json()) as Product` inside
      // @t3/api would produce for the harness's `/products/wrongshape`
      // route. @t3/web must not trust the TypeScript type; it must
      // actually parse.
      async getProduct(_id) {
        return { nope: true } as unknown as Product;
      },
      async listProducts(_params) {
        return { items: [{ nope: true } as unknown as Product], nextCursor: null };
      },
    };
    const fakeWeb = createWebClient(fakePort);

    await expect(
      fakeWeb.getProduct(1),
      "a port returning a shape that doesn't parse against ProductSchema must reject, not resolve — a bare `return await port.getProduct(id)` with no re-validation would incorrectly pass this",
    ).rejects.toThrow();

    await expect(
      fakeWeb.listProducts({}),
      "the same must hold for a malformed item inside a page's `items` array",
    ).rejects.toThrow();
  });

  test("a well-formed port response still passes through a real port unchanged", async () => {
    // Sanity check against the negative-control test above: the
    // validation added to satisfy it must not reject GOOD data too.
    const product = await web.getProduct(42);
    expect(
      product,
      "a genuinely valid product must still pass web's validation and come through unchanged",
    ).toEqual({
      id: 42,
      sku: "SKU-00042",
      name: "Vintage Doohickey 42",
      categoryId: 1,
      sellerId: 12,
      price: 48.34,
      inStock: true,
      scrapedAt: "2024-01-02T18:00:00.000Z",
    });
  });
});

// ============================================================================
// DESIGN.md gate — independent of the TypeScript checks above.
// ============================================================================

const REQUIRED_HEADINGS = [
  "## Contract surface",
  "## Versioning & evolution strategy",
  "## What breaks where when a contract changes",
  "## Runtime vs compile-time guarantees",
  "## What I'd do differently in my real monorepo",
] as const;

const PLACEHOLDER_MARKER = "[fill in";
const MIN_SECTION_CHARS = 200;

function designMdPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url)); // .../packages/e2e/tests
  return path.resolve(here, "../../../DESIGN.md"); // -> capstone root
}

function extractSection(text: string, heading: string): string | undefined {
  const idx = text.indexOf(heading);
  if (idx === -1) return undefined;
  const start = idx + heading.length;
  const rest = text.slice(start);
  const end = rest.indexOf("\n## ");
  return (end === -1 ? rest : rest.slice(0, end)).trim();
}

describe("CP3 — DESIGN.md gate", () => {
  test("DESIGN.md exists, has every required section, and every section is filled in", () => {
    const p = designMdPath();
    let text: string;
    try {
      text = readFileSync(p, "utf8");
    } catch (err) {
      throw new Error(
        `could not read DESIGN.md at ${p}: ${err instanceof Error ? err.message : String(err)}. ` +
          "It ships as a template at the capstone root — fill it in, don't delete it.",
      );
    }

    const missingHeadings = REQUIRED_HEADINGS.filter((h) => !text.includes(h));
    expect(
      missingHeadings,
      `DESIGN.md is missing required section heading(s): ${JSON.stringify(missingHeadings)}`,
    ).toEqual([]);

    for (const heading of REQUIRED_HEADINGS) {
      const content = extractSection(text, heading);
      expect(content, `could not extract content under '${heading}'`).toBeDefined();
      const body = content ?? "";

      expect(
        body.includes(PLACEHOLDER_MARKER),
        `section '${heading}' still contains the shipped '${PLACEHOLDER_MARKER}' placeholder — replace it with your own analysis grounded in what you actually built`,
      ).toBe(false);

      const charCount = body.replace(/\s/g, "").length;
      expect(
        charCount >= MIN_SECTION_CHARS,
        `section '${heading}' has only ${charCount} non-whitespace characters, expected at least ${MIN_SECTION_CHARS} — write a real analysis, not a placeholder-sized stub`,
      ).toBe(true);
    }
  });
});
