apiVersion: v1
kind: Secret
metadata:
  name: {{ include "svc-platform.fullname" . }}-shared
  labels:
    {{- include "svc-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.sharedSecret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
